// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Dismisses a toast given the ID you got when calling ShowToast
 * @param {string} toastId - ID returned for a "ShowToast" action
 * @returns {Promise.<void>}
 */
export async function DismissToast(toastId) {
	// BEGIN USER CODE
	window.toast.dismiss(toastId);
	// END USER CODE
}
