// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Shows a toast with the more basic options exposed by the react-toastify library. Returns the ID of the toast shown, to be used in dismiss or update calls.
 * @param {string} message
 * @param {Big} autoClose - timeout to autoclose the toast (in ms) - Zero means never
 * @param {"Toastify.ENU_ToastType.info"|"Toastify.ENU_ToastType.success"|"Toastify.ENU_ToastType.warning"|"Toastify.ENU_ToastType.error"|"Toastify.ENU_ToastType._default"} toastType - type of toast
 * @param {"Toastify.ENU_Position.TOP_LEFT"|"Toastify.ENU_Position.TOP_RIGHT"|"Toastify.ENU_Position.TOP_CENTER"|"Toastify.ENU_Position.BOTTOM_LEFT"|"Toastify.ENU_Position.BOTTOM_RIGHT"} position - position of the toast
 * @returns {Promise.<string>}
 */
export async function ShowToast_Basic(message, autoClose, toastType, position) {
	// BEGIN USER CODE

	const options = {
		autoClose,
		type: toastType,
		position: window.toast.POSITION[position],
	};

	window.toast(message, options);
	// END USER CODE
}
