// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package barcode.actions;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.Hashtable;
import javax.imageio.ImageIO;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GenerateBarcode extends CustomJavaAction<java.lang.Void>
{
	private final java.lang.String text;
	private final barcode.proxies.BarcodeFormat format;
	private final java.lang.Long width;
	private final java.lang.Long height;
	/** @deprecated use destination.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __destination;
	private final system.proxies.Image destination;

	public GenerateBarcode(
		IContext context,
		java.lang.String _text,
		java.lang.String _format,
		java.lang.Long _width,
		java.lang.Long _height,
		IMendixObject _destination
	)
	{
		super(context);
		this.text = _text;
		this.format = _format == null ? null : barcode.proxies.BarcodeFormat.valueOf(_format);
		this.width = _width;
		this.height = _height;
		this.__destination = _destination;
		this.destination = _destination == null ? null : system.proxies.Image.initialize(getContext(), _destination);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		MultiFormatWriter multiFormatWriter = new MultiFormatWriter();
		BarcodeFormat bcFormat = BarcodeFormat.valueOf(format.name());
		Hashtable hints = new Hashtable();
		hints.put(EncodeHintType.CHARACTER_SET, "utf-8");
		BitMatrix matrix = multiFormatWriter.encode(text, bcFormat, width.intValue(), height.intValue(), hints);
		BufferedImage bufImage = MatrixToImageWriter.toBufferedImage(matrix);
		ByteArrayOutputStream os = new ByteArrayOutputStream();
		try {
			ImageIO.write(bufImage, "png", os);
			Core.storeFileDocumentContent(getContext(), __destination,
					new ByteArrayInputStream(os.toByteArray()));
		} finally {
			os.close();
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateBarcode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
