// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as ww from '@wecom/jssdk'

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} corpID
 * @param {string} agentID
 * @returns {Promise.<void>}
 */
export async function JS_ConstructURL(corpID, agentID) {
	// BEGIN USER CODE
	
	window.location.assign(`https://login.work.weixin.qq.com/wwlogin/sso/login/?scope=snsapi_privateinfo&login_type=CorpApp&appid=${corpID}&agentid=${agentID}&redirect_uri=https%3a%2f%2fmendix.test.labull.org.cn%2fapi%2flogin&state=STATE`);
	
	// 初始化登录组件
	// const wwLogin = ww.createWWLoginPanel({
	// 	el: '.test111',
	// 	params: {
	// 		login_type: 'CorpApp',
	// 		appid: 'ww29bdf3fefbde8d9f',
	// 		agentid: '1000002',
	// 		redirect_uri: 'https://mendix.test.labull.org.cn',
	// 		// redirect_uri: 'https://work.weixin.qq.com',
	// 		state: 'WWLogin',
	// 		redirect_type: 'callback',
	// 	},
	// 	onCheckWeComLogin({ isWeComLogin }) {
	// 		console.info(isWeComLogin)
	// 	},
	// 	onLoginSuccess({ code }) {
	// 		console.info({ code })
	// 	},
	// 	onLoginFail(err) {
	// 		console.info(err)
	// 	},
	// })

	// wwLogin
	
	
	// END USER CODE
}
