name: Build Mendix Image
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t mendix-rootfs:app -f rootfs-app.dockerfile .
